services:
  frontend-app:
    image: amira100/front-app  # Build the frontend image from the frontend directory
    container_name: frontend-app  # Name of the container
    ports:
      - '5000:80'  # Map the container's port 3000 to the host machine's port 3000