# Define the name for the stack
name: backend-api-stack

services:
  # Backend API service configuration...
  backend-api:
    image: amira100/back-api  # Build the image from the current directory
    container_name: backend-api  # Name of the container
    environment:
      - MONGO_URI=mongodb://root:pass-123@mongodb:27017/book-store?authSource=admin  # MongoDB connection URI.
      - PORT=3001  # Port to run the backend API
    ports:
      - '3001:3001'  # Map the container's port 3001 to the host machine's port 3001
    depends_on:
      - mongodb  # Ensure MongoDB starts before the backend API
    networks:
      - backend-api-network  # Connect the service to the defined network

  # MongoDB service configuration
  mongodb:
    container_name: mongodb  # Name of the container
    image: mongo:7.0  # Pin a kernel-compatible MongoDB version
    restart: always  # Automatically restart MongoDB container if it stops
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  # Root username for MongoDB
      - MONGO_INITDB_ROOT_PASSWORD=pass-123  # Root password for MongoDB
      - MONGO_INITDB_DATABASE=book-store  # Initial database to create
    ports:
      - "27018:27017"  # Map the container's MongoDB port to the host's port 27017
    volumes:
      - mongodb-volume-test:/data/db  # Persist MongoDB data using a Docker volume
    networks:
      - backend-api-network  # Connect the service to the defined network
  mongo-express:
    container_name: mongo_express
    image: mongo-express
    depends_on: 
      - mongodb
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:pass-123@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password
    networks:
      - backend-api-network  # Connect the service to the defined network
      
# Define custom network for the services to communicate with each other
networks:
  backend-api-network:
    driver: bridge  # Use the default bridge driver for the network

# Define named volume to persist MongoDB data
volumes:
  mongodb-volume:
  mongodb-volume-test:
